In [1]:
import numpy as np
import random

In [22]:
#1

A = np.zeros((10,), dtype=int)
for i in range(0,10):
    A[i] = i+1

A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#2

B = np.zeros((3,3), dtype=int)
B

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
#3

C = np.zeros((5,5), dtype=int)

for i in range(0,5):
    for j in range(0, 5):
        C[i,j] = random.randint(1,10)
        
C

array([[ 9,  6,  4,  7,  1],
       [ 3,  5,  7,  6,  1],
       [ 5,  4,  4,  1,  1],
       [ 1,  1, 10,  6,  6],
       [ 7,  3,  7, 10,  9]])

In [5]:
#4

D = np.zeros((4,4))

for i in range(0,4):
    for j in range(0, 4):
        D[i,j] = random.random()
        
D        

array([[0.84697174, 0.07436609, 0.41799256, 0.07533517],
       [0.30089352, 0.43294187, 0.82228571, 0.89144822],
       [0.79206809, 0.22206436, 0.39661537, 0.42533234],
       [0.53105142, 0.17523983, 0.05994669, 0.51762853]])

In [6]:
#5

E = np.random.randint(1,11, size=5)
F = np.random.randint(1,11, size=5)

sum = E+F
sub = E-F
mult = E*F

print(E, F)
print(sum,sub,mult)

[ 2 10  3  1  3] [4 1 7 4 3]
[ 6 11 10  5  6] [-2  9 -4 -3  0] [ 8 10 21  4  9]


In [7]:
#6

G = np.random.randint(0,11, size=7)
H = np.random.randint(0,11, size=7)

print(G, H)
print(np.dot(G,H))

[7 5 8 1 9 9 6] [2 0 3 5 4 9 5]
190


In [12]:
#7

I = np.random.randint(1,11, size=(2,2))
K = np.random.randint(1,11, size=(2,3))

print(I)
print(K)
print(np.dot(I,K))

[[ 6  5]
 [10  3]]
[[3 5 5]
 [1 6 5]]
[[23 60 55]
 [33 68 65]]


In [13]:
#8

J = np.random.randint(1,11, size=(3,3))
L = np.linalg.inv(J)
L

array([[ 9.91270558e-18,  3.20000000e-01, -1.20000000e-01],
       [-1.11111111e-01,  2.66666667e-02,  1.28888889e-01],
       [ 1.11111111e-01, -2.26666667e-01,  7.11111111e-02]])

In [15]:
#9

O = np.random.random(size=(4,4))
print(O)
print(O.T)

array([[0.23528562, 0.02718902, 0.53637794, 0.07435746],
       [0.70377606, 0.51901034, 0.07258913, 0.13728974],
       [0.04004246, 0.5202598 , 0.19519095, 0.69914514],
       [0.11718447, 0.49884984, 0.62505116, 0.73973975]])

In [19]:
#10

matrix = np.random.randint(1,11, size=(3,4))
vector = np.random.randint(1,11, size=4)

print(matrix)
print(vector)
print(np.dot(matrix, vector))

[[ 1  1  6  1]
 [ 4  9  3  4]
 [ 3 10 10  6]]
[ 8  6 10  7]
[ 81 144 226]


In [20]:
#11

matrix = np.random.random( size=(3,4))
vector = np.random.random( size=4)

print(matrix)
print(vector)
print(np.dot(matrix, vector))

[[0.96427002 0.64715125 0.80311131 0.57582952]
 [0.15690074 0.20576775 0.20216901 0.25662874]
 [0.18586628 0.52916872 0.13874252 0.26390394]]
[0.1151981  0.72927995 0.90490381 0.78236499]
[1.76028384 0.55185781 0.73934142]


In [24]:
#12 #13

M = np.random.randint(1,11, size=(2,2))
K =  np.random.randint(1,11, size=(2,2))

print(M)
print(K)
print(M*K)
print(np.dot(K,M))

[[ 3 10]
 [ 9  5]]
[[5 2]
 [4 6]]
[[15 20]
 [36 30]]


In [25]:
#14

M = np.random.randint(1,101, size=(5,5))
sum = M.sum()

print(M)
print(sum)

[[85  9 25 38 29]
 [41 34 76 51 44]
 [83 67 11 81 12]
 [80 27 88 98 68]
 [85 30 68 89 87]]
1406


In [26]:
#15
A = np.random.randint(1,11, size=(4,4))
B = np.random.randint(1,11, size=(4,4))

print(A)
print(B)
print(A-B)


[[ 5  8  5  4]
 [10  1  9  9]
 [ 2  3 10  4]
 [ 5  9  6  6]]
[[7 8 8 2]
 [9 2 7 1]
 [4 3 7 9]
 [3 2 3 3]]
[[-2  0 -3  2]
 [ 1 -1  2  8]
 [-2  0  3 -5]
 [ 2  7  3  3]]


In [35]:
#16

M = np.random.random(size=(3,3))

sums = np.sum(M, axis=1)
column = sums.reshape(3,1)

print(M)
print(sums)
print(column)

[[0.07904645 0.75556279 0.44686274]
 [0.83386527 0.83338889 0.89157512]
 [0.04674142 0.30376176 0.45279655]]
[1.28147197 2.55882929 0.80329973]
[[1.28147197]
 [2.55882929]
 [0.80329973]]


In [36]:
#17

A = np.random.randint(1,11, size=(3,4))
squared = np.square(A)

print(A)
print(squared)


[[ 7  2  6 10]
 [ 8 10  6  4]
 [ 7 10 10  5]]
[[ 49   4  36 100]
 [ 64 100  36  16]
 [ 49 100 100  25]]


In [37]:
#18

vector = np.random.randint(1,51, size=4)
sqrt = np.sqrt(vector)

print(vector)
print(sqrt)

[ 9 39 18 13]
[3.         6.244998   4.24264069 3.60555128]
